### PR TITLE
Streamline includes

### PR DESCRIPTION
**Pull request by Krzmbrzl**
This adds missing includes such that each file should now be
self-contained, which will hopefully avoid any issues in the future
where changing one header somewhere breaks seemingly completely
unrelated sources.
This has been done with the help of the include-what-you-use tool.

### CODE REVIEW

**Comment by Krzmbrzl** [comment]
The CI on macOS fails with the following error:
```
[73/537] Building CXX object CMakeFiles/SeQuant.dir/SeQuant/core/eval_expr.cpp.o
FAILED: CMakeFiles/SeQuant.dir/SeQuant/core/eval_expr.cpp.o 
/usr/local/bin/ccache /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_LOCALE_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBTAS_ASSERT_THROWS=1 -DBTAS_HAS_BLAS_LAPACK=1 -DBTAS_HAS_BOOST_CONTAINER=1 -DBTAS_HAS_BOOST_ITERATOR=1 -DBTAS_HAS_BOOST_SERIALIZATION=1 -DBTAS_TARGET_MAX_INDEX_RANK=6 -DLAPACK_COMPLEX_CPP=1 -DMADNESS_DISABLE_WORLD_GET_DEFAULT=1 -DMADNESS_MPI_HEADER=\"/usr/local/Cellar/open-mpi/4.1.5/include/mpi.h\" -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -DSEQUANT_HAS_EIGEN=1 -D_MPICC_H -I/Users/runner/work/SeQuant/SeQuant -I/Users/runner/work/SeQuant/SeQuant/build -I/Users/runner/work/SeQuant/SeQuant/build/_deps/rangev3-src/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/tiledarray-src/src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/tiledarray-build/src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/madness-src/src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/madness-build/src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/madness-build/src/madness/world -I/Users/runner/work/SeQuant/SeQuant/build/_deps/madness-src/src/madness/world -I/Users/runner/work/SeQuant/SeQuant/build/_deps/btas-src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/blaspp-build/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/blaspp-src/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/lapackpp-build/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/lapackpp-src/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/umpire-src/src -I/Users/runner/work/SeQuant/SeQuant/build/_deps/umpire-src/src/umpire/tpl/camp/include -I/Users/runner/work/SeQuant/SeQuant/build/_deps/umpire-build/include -isystem /usr/local/Cellar/boost@1.76/1.76.0_4/include -isystem /usr/local/Cellar/open-mpi/4.1.5/include -isystem /usr/local/include/eigen3 -O3 -DNDEBUG -std=c++17 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6 -fPIC -MD -MT CMakeFiles/SeQuant.dir/SeQuant/core/eval_expr.cpp.o -MF CMakeFiles/SeQuant.dir/SeQuant/core/eval_expr.cpp.o.d -o CMakeFiles/SeQuant.dir/SeQuant/core/eval_expr.cpp.o -c /Users/runner/work/SeQuant/SeQuant/SeQuant/core/eval_expr.cpp
In file included from /Users/runner/work/SeQuant/SeQuant/SeQuant/core/eval_expr.cpp:1:
In file included from /Users/runner/work/SeQuant/SeQuant/SeQuant/core/eval_expr.hpp:6:
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/index.hpp:338:27: error: no matching function for call to 'to_wolfram'
    ((result += ((L","s + ::sequant::to_wolfram(std::forward<Attrs>(attrs))))),
                          ^~~~~~~~~~~~~~~~~~~~~
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/tensor.hpp:275:19: note: in instantiation of function template specialization 'sequant::Index::to_wolfram<sequant::BraKetPos>' requested here
      result += i.to_wolfram(BraKetPos::ket) + L",";
                  ^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/rational.hpp:165:21: note: candidate function not viable: no known conversion from 'sequant::BraKetPos' to 'const sequant::rational' (aka 'const number<rational_adaptor<cpp_int_backend<>>>') for 1st argument
inline std::wstring to_wolfram(const rational& t) {
                    ^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/expr.hpp:1503:21: note: candidate function not viable: no known conversion from 'sequant::BraKetPos' to 'const sequant::ExprPtr' for 1st argument
inline std::wstring to_wolfram(const ExprPtr &exprptr) {
                    ^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/space.hpp:620:14: note: candidate function not viable: no known conversion from 'sequant::BraKetPos' to 'const sequant::IndexSpace' for 1st argument
std::wstring to_wolfram(const IndexSpace &space);
             ^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/rational.hpp:160:21: note: candidate template ignored: could not match 'number<type-parameter-0-0, expression_template_default<type-parameter-0-0>::value>' against 'sequant::BraKetPos'
inline std::wstring to_wolfram(
                    ^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/wolfram.hpp:15:1: note: candidate template ignored: requirement 'meta::has_memfn_to_wolfram_v<sequant::BraKetPos>' was not satisfied [with T = sequant::BraKetPos]
to_wolfram(T &&t) {
^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/wolfram.hpp:21:1: note: candidate template ignored: requirement 'std::is_arithmetic_v<sequant::BraKetPos>' was not satisfied [with T = sequant::BraKetPos]
to_wolfram(T &&t) {
^
/Users/runner/work/SeQuant/SeQuant/SeQuant/core/wolfram.hpp:27:14: note: candidate template ignored: could not match 'complex<type-parameter-0-0>' against 'sequant::BraKetPos'
std::wstring to_wolfram(const std::complex<T> &t) {
             ^
1 error generated.
```

However, I fail to reproduce this issue (on Linux) and I also don't see how this can come about. My understanding of this error message is that `eval_expr.cpp` includes `tensor.hpp` and that contains the function
https://github.com/ValeevGroup/SeQuant/blob/7a7364768e8f2052feec87eb07556e34ad0f1019/SeQuant/core/tensor.hpp#L243-L259
that, as you can see, calls `Index::to_wolfram(BraKetPos)`:
https://github.com/ValeevGroup/SeQuant/blob/7a7364768e8f2052feec87eb07556e34ad0f1019/SeQuant/core/index.hpp#L303-L332

The issue now is that for some reason that I fail to understand, Apple Clang doesn't find
https://github.com/ValeevGroup/SeQuant/blob/7a7364768e8f2052feec87eb07556e34ad0f1019/SeQuant/core/attr.hpp#L54-L57
that is called from within the `Index::to_wolfram` template function.
This is even though `attr.hpp` is clearly included at the top of `tensor.hpp`, meaning that it must have been processed _before_ even encounting `Tensor::to_wolfram`.

I kinda have the feeling that this is likely a bug in Apple Clang as I was able to build this version of the code just fine using either GCC or Clang on Linux.

**Comment by evaleev** [comment]
@Krzmbrzl thanks ...

- if we are going to do this we might as well fix the #include paths themselves. Inclusions like `#include "attr.h"` are extremely fragile, need to be `"SeQuant/core/attr.h"` or (better, in my opinion) `<SeQuant/core/attr.h>` ...
- can invocation of `iwyu` be added to the git hooks provided with SeQuant?

**Comment by Krzmbrzl** [comment]
> if we are going to do this we might as well fix the #include paths themselves. Inclusions like #include "attr.h" are extremely fragile, need to be "SeQuant/core/attr.h" or (better, in my opinion) <SeQuant/core/attr.h> ...

Agreed.

> can invocation of iwyu be added to the git hooks provided with SeQuant?

There might be a way, but it would probably not be particularly helpful. iwyu has many false-positives as it needs to explicitly know a library's include structure such that it can know which are the public headers that users should include and then only suggest those instead of suggesting to replace the public header with a private implementation header.
So atm using iwyu requires a fair amount of manual tweaking, which makes it rather unsuited for automatic application.

**Comment by Krzmbrzl** [comment]
@evaleev I rebased this against current master and adapted the include style to what you suggested

**Comment by Krzmbrzl** [comment]
Rebased against current master

**Comment by bimalgaudel** [comment]
@Krzmbrzl https://pre-commit.com/ might be useful to automatically get source code formatted before you commit. We use that.

**Comment by Krzmbrzl** [comment]
>  [pre-commit.com](https://pre-commit.com/) might be useful to automatically get source code formatted before you commit. We use that.

Thanks for the hint. I prefer separating formatting changes from code changes in my commits though. That tends to make using `git blame` easier :eyes:

**Comment by Krzmbrzl** [comment]
@evaleev I rebased this PR against current master again. Would you mind taking another look at this?

**Pull request merged**
